// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package request

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson41634fcbDecodeTestFPRCPkgModelsHttpRequest(in *jlexer.Lexer, out *UserRegistrationRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user":
			easyjson41634fcbDecodeTestFPRCPkgModelsHttpRequest1(in, &out.User)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson41634fcbEncodeTestFPRCPkgModelsHttpRequest(out *jwriter.Writer, in UserRegistrationRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix[1:])
		easyjson41634fcbEncodeTestFPRCPkgModelsHttpRequest1(out, in.User)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserRegistrationRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson41634fcbEncodeTestFPRCPkgModelsHttpRequest(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserRegistrationRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson41634fcbEncodeTestFPRCPkgModelsHttpRequest(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserRegistrationRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson41634fcbDecodeTestFPRCPkgModelsHttpRequest(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserRegistrationRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson41634fcbDecodeTestFPRCPkgModelsHttpRequest(l, v)
}
func easyjson41634fcbDecodeTestFPRCPkgModelsHttpRequest1(in *jlexer.Lexer, out *UserRegistrationRequestUser) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "internal_name":
			out.InternalName = string(in.String())
		case "public_name":
			out.PublicName = string(in.String())
		case "password":
			out.Password = string(in.String())
		case "secret_code":
			out.SecretCode = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson41634fcbEncodeTestFPRCPkgModelsHttpRequest1(out *jwriter.Writer, in UserRegistrationRequestUser) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"internal_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.InternalName))
	}
	{
		const prefix string = ",\"public_name\":"
		out.RawString(prefix)
		out.String(string(in.PublicName))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"secret_code\":"
		out.RawString(prefix)
		out.String(string(in.SecretCode))
	}
	out.RawByte('}')
}
